# Generated by Django 2.0 on 2018-02-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_user', models.CharField(max_length=30)),
                ('M_BMI', models.IntegerField()),
                ('M_Height', models.IntegerField()),
                ('M_Weight', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
